version: "3.3"

services:
  backend:
    container_name: song-vote-api
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 42069:42069
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PWD}
    depends_on:
      - db
    logging:
      driver: none

volumes:
  db_data:
