name: Deploy To Personal Server

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    steps:
      - name: Generate build folder
        uses: actions/checkout@master
        uses: actions/setup-node@master
        run: npm install
        run: npm run build
        uses: actions/upload-artifact@v1
        with:
          name: frontendBuild
          path: ./frontend/build
      - name: executing remote ssh commands using password
        uses: konstantinjdobler/ssh-action@master
        with:
          host: ${{ secrets.PERSONAL_SERVER_HOST }}
          username: ${{ secrets.PERSONAL_SERVER_USER }}
          password: ${{ secrets.PERSONAL_SERVER_PASSWORD }}
          timeout: 30m
          command_timeout: 30m
          script: |
            echo "Shutting down server"
            cd ~/projects/spotify-takeover/backend
            docker-compose down

            echo "Checking out commit with SHA: ${{github.sha}}"
            cd ~/projects/spotify-takeover
            git fetch
            git checkout -f ${{github.sha}}

            echo "Updating frontend"
            cd frontend
            echo "Updating frontend dependencies"
            npm i --only=production
            echo "Running frontend build"
            export TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling

            npm run build

            echo "Updating backend"
            cd ../backend
            echo "Updating backend dependencies"
            npm i --only=production
            echo "Building server"
            docker-compose up -d --build 


            echo "Reloading nginx"
            sudo nginx -s reload
